const newsData = [
  {
    id: 1,
    title: "Video Tutorial - How to Clone and Pull GitHub Repo",
    date: "Sun, 22 Mar 2026",
    description: "How to create a clone and pull updates from a GitHub Repo.",
    link: "#",
  },
  {
    id: 2,
    title: "Blog - How to Clone and Pull GitHub Repo",
    date: "Sun, 22 Mar 2026",
    description: "How to create a clone and pull updates from a GitHub Repo.",
    link: "#",
  },
  {
    id: 3,
    title: "Video Tutorial - Java HashSet Explained: Why equals() and hashCode() Matter (With Examples)",
    date: "Sat, 21 Mar 2026",
    description: "Learn why overriding equals() and hashCode() is crucial when using user-defined class with HashSet class.",
    link: "#",
  },
  {
    id: 4,
    title: "Blog - Looking back at 2025",
    date: "Thu, 01 Jan 2026",
    description: "A summary of important events of my life in 2025.",
    link: "#",
  },
  {
    id: 5,
    title: "Video Tutorial - Getting started with Ollama",
    date: "Thu, 27 Nov 2025",
    description: "In this video, you will learn how to install Ollama, download models and access them using Ollama and programmatically.",
    link: "#",
  },
  {
    id: 6,
    title: "Video Tutorial - Difference between Active and Inactive Relationship in Power BI",
    date: "Wed, 26 Nov 2025",
    description: "In this video, you will learn what is the difference between Active and Inactive Relationship in Power BI and how to use Inactive relationship in Measures",
    link: "#",
  },
  {
    id: 7,
    title: "Video Tutorial - How to install SQL Server Express Edition and SQL Server Management Studio",
    date: "Tue, 25 Nov 2025",
    description: "In this video, you will learn how to install SQL Server Express Edition and connect to it from SQL Server Management Studio.",
    link: "#",
  },
  {
    id: 8,
    title: "Video Tutorial - Loading data from SQLite Database into Power BI using Python",
    date: "Sat, 22 Nov 2025",
    description: "In this video, you will learn how to write Python script to get data from SQLite database using Pandas dataframe and load that into Power BI.",
    link: "#",
  },
  {
    id: 9,
    title: "Blog - Looking back at 2024",
    date: "Wed, 01 Jan 2025",
    description: "A summary of important events of my life in 2024.",
    link: "#",
  },
   {
    id: 10,
    title: "Video Course - Test Your Python Knowledge",
    date: "Sat, 23 Nov 2024",
    description: "Here is my new on demand video course - Test Your Python Knowledge - made available on Udemy.com",
    link: "#",
  },
  {
    id: 11,
    title: "Video Tutorial - How Characters Are Stored in Computer Memory",
    date: "Thu, 07 Nov 2024",
    description: "In this video, you will understand how characters are stored in computer memory using ASCII codes and how much memory it occupies.",
    link: "#",
  },
  {
    id: 12,
    title: "Video Tutorial - Getting started with Power BI",
    date: "Thu, 07 Nov 2024",
    description: "In this video, you will learn how to install Power BI Desktop, get data from an excel file and create a report.",
    link: "#",
  },
  {
    id: 13,
    title: "Video Course - JavaScript for Beginners",
    date: "Thu, 14 Mar 2024",
    description: "Here is my new on demand video course - JavaScript for Beginners - made available on Udemy.com",
    link: "#",
  },
  {
    id: 14,
    title: "Blog - Accessing MongoDB from Node.js",
    date: "Mon, 05 Feb 2024",
    description: "In this blog, you learn how to perform CRUD operations on documents in MongoDB from Node.js",
    link: "#",
  },
  {
    id: 15,
    title: "Video Tutorial - Getting started with Anaconda and JupyterLab",
    date: "Sat, 03 Feb 2024",
    description: "In this video, you will learn how to install and get started with Anaconda and JupyterLab for Data Science.",
    link: "#",
  },
  {
    id: 16,
    title: "Video Tutorial - Shallow Copy vs Deep Copy in Python",
    date: "Sat, 03 Feb 2024",
    description: "In this video, you will learn the difference between shallow copy and deep copy in Python and how to implement them.",
    link: "#",
  },{
    id: 17,
    title: "Video Tutorial - How to use JSON Server to create MOCK API",
    date: "Sat, 20 Jan 2024",
    description: "In this video, you learn how to use JSON Server to create MOCK API to test your Front-end Apps.",
    link: "#",
  },
  {
    id: 18,
    title: "Blog - Looking back at 2023",
    date: "Mon, 01 Jan 2024",
    description: "A summary of important events of my life in 2023.",
    link: "#",
  },
  {
    id: 19,
    title: "Video Tutorial - How to use JPA (using Hibernate) with Oracle Database 19c using Eclipse",
    date: "Mon, 27 Nov 2023",
    description: "In this video, you learn how to use JPA (using Hibernate) with Oracle Database 19c using Eclipse.",
    link: "#",
  },
  {
    id: 20,
    title: "Video Tutorial - Destructuring Assignment in JavaScript",
    date: "Mon, 27 Nov 2023",
    description: "Learn how to use Destructuring Assignment with Arrays and Objects in JavaScript.",
    link: "#",
  },
  {
    id: 21,
    title: "Blog - JPA + Oracle Database 19c",
    date: "Fri, 24 Nov 2023",
    description: "This blog shows how to use JPA (using Hibernate) to access Oracle Database 19c.",
    link: "#",
  },
  {
    id: 22,
    title: "Video Tutorial - Arrow Function Expression in JavaScript",
    date: "Fri, 10 Nov 2023",
    description: "Learn how to use Arrow Function Expression in JavaScript with methods like filter(), map() and forEach().",
    link: "#",
  },
   {
    id: 23,
    title: "Video Tutorial - Spread Operator in JavaScript",
    date: "Mon, 06 Nov 2023",
    description: "Learn how to use Spread Operator in JavaScript",
    link: "#",
  },
  {
    id: 24,
    title: "Blog - 25 Years of Srikanth Technologies",
    date: "Sat, 21 Oct 2023",
    description: "In this blog, I share 25 years journey of Srikanth Technologies.",
    link: "#",
  },
  {
    id: 25,
    title: "Blog - 32 years and counting",
    date: "Mon, 04 Sep 2023",
    description: "This blog is about my 32 years of experience and GIFT.",
    link: "#",
  },
   {
    id: 26,
    title: "Blog - What I learned in the last 6 years",
    date: "Sat, 26 Aug 2023",
    description: "I listed the technologies I learned in the last 6 years.",
    link: "#",
  },
  {
    id: 27,
    title: "Blog - I am now AWS Certified Cloud Practitioner",
    date: "Mon, 26 Jun 2023",
    description: "I share details of my new certification - AWS Cloud Practitioner.",
    link: "#",
  },
  {
    id: 28,
    title: "Video Tutorial - How to use Comparator interface in Java",
    date: "Mon, 05 Jun 2023",
    description: "Learn how to use Comparator interface in Java",
    link: "#",
  },
  {
    id: 29,
    title: "Blog - Converting table rows to and from JSON",
    date: "Wed, 29 Mar 2023",
    description: "In this blog you learn how to convert data in table to JSON and load data from JSON to table.",
    link: "#",
  },
  {
    id: 30,
    title: "Blog - How to install Python libraries in offline mode",
    date: "Tue, 28 Mar 2023",
    description: "Learn how to install Python libraries on a system that is NOT connected to Internet (offline).",
    link: "#",
  },
  {
    id: 31,
    title: "Blog - How to use Excel in Python using openpyxl library",
    date: "Mon, 27 Mar 2023",
    description: "Learn how to write and read excel files from Python using openpyxl library",
    link: "#",
  },
  {
    id: 32,
    title: "Blog - Looking back at 2022",
    date: "Sun, 01 Jan 2023",
    description: "A summary of important events of my life in 2022.",
    link: "#",
  },
   {
    id: 33,
    title: "Blog - Todos using React and Redux",
    date: "Sat, 06 Aug 2022",
    description: "In this blog you learn how to use Redux to manage state of Todos application in React.",
    link: "#",
  }, 
  {
    id: 34,
    title: "Blog - Using Redux in React",
    date: "Fri, 05 Aug 2022",
    description: "In this blog you learn how to use Redux library to manage state in a React Application.",
    link: "#",
  },
  {
    id: 35,
    title: "Blog - Todos Application in React using LocalStorage",
    date: "Sat, 09 Jul 2022",
    description: "In this blog you learn how to develop a Todos application using React and store data in LocalStorage of Browser.",
    link: "#",
  },
  {
    id: 36,
    title: "Blog - Installing HR Schema in Oracle Database 21c Express Edition (XE)",
    date: "Tue, 21 Jun 2022",
    description: "This blog explains steps to be taken to install HR Schema in Oracle Database 21c XE",
    link: "#",
  },
  {
    id: 37,
    title: "Video Tutorial - Mutable and Immutable objects in Python",
    date: "Fri, 25 Feb 2022",
    description: "Learn what is the difference between Mutable and Immutable objects in Python.",
    link: "#",
  },
   {
    id: 38,
    title: "Video Tutorial - How to pass a function as a parameter to another function in Python",
    date: "Wed, 26 Jan 2022",
    description: "Learn how to use pass a function as a parameter to another function in Python",
    link: "#",
  },
   {
    id: 39,
    title: "Video Tutorial - How to use filter() function in Python",
    date: "Wed, 26 Jan 2022",
    description: "Learn how to use filter() function in Python to filter elements in a collection",
    link: "#",
  },
  {
    id: 40,
    title: "Video Tutorial - How to use sorted() function in Python",
    date: "Wed, 26 Jan 2022",
    description: "Learn how to use key parameter in sorted() function in Python",
    link: "#",
  },
  {
    id: 41,
    title: "Video Tutorial - How to use map() function in Python",
    date: "Tue, 25 Jan 2022",
    description: "Learn how to use map() function in Python",
    link: "#",
  },
  {
    id: 42,
    title: "Video Tutorial - Overloading in Python",
    date: "Tue, 25 Jan 2022",
    description: "Learn why Python doesn't support overloading",
    link: "#",
  },
];
export default newsData;